name: medreminder
description: "MedCare+ — Smart Medicine Reminder System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Notifications & Scheduling
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4



  # Local Storage
  shared_preferences: ^2.5.2

  # Image Handling
  image_picker: ^1.1.2
  path_provider: ^2.1.5

  # Charts & UI
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1


  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
